// =============================================================================
// THE GAMES ROOM - PREMIUM SEO DATABASE
// Mesas de billar, futbolines, dardos, air hockey
// Multi-language, Multi-country, High-Intent Keywords
// =============================================================================

export const LOCALES = {
  es: { name: 'Español', countries: ['spain', 'mexico', 'argentina', 'colombia', 'chile', 'peru'] },
  en: { name: 'English', countries: ['usa', 'uk', 'canada', 'australia', 'ireland'] },
  de: { name: 'Deutsch', countries: ['germany', 'austria', 'switzerland'] },
  fr: { name: 'Français', countries: ['france', 'belgium'] },
  it: { name: 'Italiano', countries: ['italy', 'switzerland'] },
  pt: { name: 'Português', countries: ['portugal', 'brazil'] },
  nl: { name: 'Nederlands', countries: ['netherlands', 'belgium'] },
  pl: { name: 'Polski', countries: ['poland'] },
  cs: { name: 'Čeština', countries: ['czechia'] },
  el: { name: 'Ελληνικά', countries: ['greece'] },
} as const;

export type Locale = keyof typeof LOCALES;
export const SUPPORTED_LOCALES = Object.keys(LOCALES) as Locale[];

// =============================================================================
// CITIES BY COUNTRY
// =============================================================================

export const CITIES_BY_COUNTRY: Record<string, { name: string; slug: string; population: number }[]> = {
  spain: [
    // Major cities
    { name: 'Madrid', slug: 'madrid', population: 3223000 },
    { name: 'Barcelona', slug: 'barcelona', population: 1620000 },
    { name: 'Valencia', slug: 'valencia', population: 791000 },
    { name: 'Sevilla', slug: 'sevilla', population: 688000 },
    { name: 'Zaragoza', slug: 'zaragoza', population: 666000 },
    { name: 'Málaga', slug: 'malaga', population: 571000 },
    { name: 'Murcia', slug: 'murcia', population: 447000 },
    { name: 'Palma de Mallorca', slug: 'palma', population: 416000 },
    { name: 'Bilbao', slug: 'bilbao', population: 346000 },
    { name: 'Alicante', slug: 'alicante', population: 334000 },
    { name: 'Córdoba', slug: 'cordoba', population: 325000 },
    { name: 'Valladolid', slug: 'valladolid', population: 298000 },
    { name: 'Vigo', slug: 'vigo', population: 292000 },
    { name: 'Gijón', slug: 'gijon', population: 271000 },
    { name: 'Granada', slug: 'granada', population: 232000 },
    { name: 'A Coruña', slug: 'a-coruna', population: 245000 },
    { name: 'Vitoria', slug: 'vitoria', population: 252000 },
    { name: 'Elche', slug: 'elche', population: 230000 },
    { name: 'Oviedo', slug: 'oviedo', population: 220000 },
    { name: 'Santa Cruz de Tenerife', slug: 'santa-cruz-tenerife', population: 207000 },
    { name: 'Badalona', slug: 'badalona', population: 215000 },
    { name: 'Cartagena', slug: 'cartagena', population: 214000 },
    { name: 'Terrassa', slug: 'terrassa', population: 220000 },
    { name: 'Jerez de la Frontera', slug: 'jerez', population: 212000 },
    { name: 'Sabadell', slug: 'sabadell', population: 213000 },
    { name: 'Móstoles', slug: 'mostoles', population: 207000 },
    { name: 'Alcalá de Henares', slug: 'alcala-henares', population: 195000 },
    { name: 'Pamplona', slug: 'pamplona', population: 203000 },
    { name: 'Fuenlabrada', slug: 'fuenlabrada', population: 194000 },
    { name: 'Almería', slug: 'almeria', population: 198000 },
    { name: 'Leganés', slug: 'leganes', population: 189000 },
    { name: 'San Sebastián', slug: 'san-sebastian', population: 187000 },
    { name: 'Santander', slug: 'santander', population: 172000 },
    { name: 'Burgos', slug: 'burgos', population: 176000 },
    { name: 'Castellón', slug: 'castellon', population: 171000 },
    { name: 'Albacete', slug: 'albacete', population: 173000 },
    { name: 'Getafe', slug: 'getafe', population: 183000 },
    { name: 'Alcorcón', slug: 'alcorcon', population: 170000 },
    { name: 'Logroño', slug: 'logrono', population: 151000 },
    { name: 'Badajoz', slug: 'badajoz', population: 150000 },
    { name: 'Salamanca', slug: 'salamanca', population: 144000 },
    { name: 'Huelva', slug: 'huelva', population: 143000 },
    { name: 'Marbella', slug: 'marbella', population: 147000 },
    { name: 'Lleida', slug: 'lleida', population: 138000 },
    { name: 'Tarragona', slug: 'tarragona', population: 132000 },
    { name: 'León', slug: 'leon', population: 124000 },
    { name: 'Cádiz', slug: 'cadiz', population: 116000 },
    { name: 'Jaén', slug: 'jaen', population: 112000 },
    { name: 'Ourense', slug: 'ourense', population: 105000 },
    { name: 'Girona', slug: 'girona', population: 103000 },
    { name: 'Lugo', slug: 'lugo', population: 98000 },
    { name: 'Santiago de Compostela', slug: 'santiago-compostela', population: 97000 },
    { name: 'Cáceres', slug: 'caceres', population: 96000 },
    { name: 'Lorca', slug: 'lorca', population: 94000 },
    { name: 'Toledo', slug: 'toledo', population: 85000 },
    { name: 'Pontevedra', slug: 'pontevedra', population: 83000 },
    { name: 'Palencia', slug: 'palencia', population: 78000 },
    { name: 'Ciudad Real', slug: 'ciudad-real', population: 75000 },
    { name: 'Zamora', slug: 'zamora', population: 61000 },
    { name: 'Ávila', slug: 'avila', population: 57000 },
    { name: 'Cuenca', slug: 'cuenca', population: 55000 },
    { name: 'Huesca', slug: 'huesca', population: 53000 },
    { name: 'Segovia', slug: 'segovia', population: 51000 },
    { name: 'Soria', slug: 'soria', population: 39000 },
    { name: 'Teruel', slug: 'teruel', population: 35000 },
    { name: 'Ibiza', slug: 'ibiza', population: 50000 },
    { name: 'Benidorm', slug: 'benidorm', population: 68000 },
    { name: 'Torrevieja', slug: 'torrevieja', population: 83000 },
    { name: 'Reus', slug: 'reus', population: 106000 },
    { name: 'Mataró', slug: 'mataro', population: 128000 },
    { name: 'Santa Coloma', slug: 'santa-coloma', population: 118000 },
    { name: 'Algeciras', slug: 'algeciras', population: 121000 },
    { name: 'Torrejón de Ardoz', slug: 'torrejon-ardoz', population: 130000 },
    { name: 'Parla', slug: 'parla', population: 130000 },
    { name: 'Alcobendas', slug: 'alcobendas', population: 117000 },
    { name: 'Dos Hermanas', slug: 'dos-hermanas', population: 135000 },
    { name: 'Roquetas de Mar', slug: 'roquetas-mar', population: 97000 },
    { name: 'San Fernando', slug: 'san-fernando', population: 95000 },
    { name: 'Pozuelo de Alarcón', slug: 'pozuelo-alarcon', population: 87000 },
    { name: 'Las Rozas', slug: 'las-rozas', population: 99000 },
    { name: 'San Cugat', slug: 'san-cugat', population: 91000 },
    { name: 'Rubí', slug: 'rubi', population: 77000 },
    { name: 'Manresa', slug: 'manresa', population: 77000 },
    { name: 'Vic', slug: 'vic', population: 46000 },
    { name: 'Figueres', slug: 'figueres', population: 47000 },
    { name: 'Blanes', slug: 'blanes', population: 39000 },
    { name: 'Lloret de Mar', slug: 'lloret-mar', population: 37000 },
    { name: 'Sitges', slug: 'sitges', population: 29000 },
    { name: 'Calella', slug: 'calella', population: 19000 },
    { name: 'Tossa de Mar', slug: 'tossa-mar', population: 6000 },
    { name: 'Cadaqués', slug: 'cadaques', population: 3000 },
    { name: 'Roses', slug: 'roses', population: 20000 },
    { name: 'Empuriabrava', slug: 'empuriabrava', population: 8000 },
    { name: 'Salou', slug: 'salou', population: 27000 },
    { name: 'Cambrils', slug: 'cambrils', population: 34000 },
    { name: 'Peñíscola', slug: 'peniscola', population: 8000 },
    { name: 'Benicàssim', slug: 'benicassim', population: 18000 },
    { name: 'Gandía', slug: 'gandia', population: 74000 },
    { name: 'Dénia', slug: 'denia', population: 42000 },
    { name: 'Jávea', slug: 'javea', population: 27000 },
    { name: 'Calpe', slug: 'calpe', population: 21000 },
    { name: 'Altea', slug: 'altea', population: 22000 },
    { name: 'Villajoyosa', slug: 'villajoyosa', population: 34000 },
    { name: 'Santa Pola', slug: 'santa-pola', population: 34000 },
    { name: 'Guardamar', slug: 'guardamar', population: 16000 },
    { name: 'Orihuela Costa', slug: 'orihuela-costa', population: 25000 },
    { name: 'Pilar de la Horadada', slug: 'pilar-horadada', population: 25000 },
    { name: 'San Pedro del Pinatar', slug: 'san-pedro-pinatar', population: 25000 },
    { name: 'Los Alcázares', slug: 'los-alcazares', population: 16000 },
    { name: 'La Manga', slug: 'la-manga', population: 5000 },
    { name: 'Águilas', slug: 'aguilas', population: 35000 },
    { name: 'Mazarrón', slug: 'mazarron', population: 36000 },
    { name: 'Mojácar', slug: 'mojacar', population: 8000 },
    { name: 'Vera', slug: 'vera', population: 16000 },
    { name: 'Garrucha', slug: 'garrucha', population: 9000 },
    { name: 'Carboneras', slug: 'carboneras', population: 8000 },
    { name: 'Níjar', slug: 'nijar', population: 31000 },
    { name: 'El Ejido', slug: 'el-ejido', population: 88000 },
    { name: 'Adra', slug: 'adra', population: 25000 },
    { name: 'Almuñécar', slug: 'almunecar', population: 27000 },
    { name: 'Motril', slug: 'motril', population: 60000 },
    { name: 'Salobreña', slug: 'salobrena', population: 13000 },
    { name: 'Nerja', slug: 'nerja', population: 22000 },
    { name: 'Torrox', slug: 'torrox', population: 17000 },
    { name: 'Vélez-Málaga', slug: 'velez-malaga', population: 81000 },
    { name: 'Rincón de la Victoria', slug: 'rincon-victoria', population: 48000 },
    { name: 'Torremolinos', slug: 'torremolinos', population: 69000 },
    { name: 'Benalmádena', slug: 'benalmadena', population: 69000 },
    { name: 'Fuengirola', slug: 'fuengirola', population: 81000 },
    { name: 'Mijas', slug: 'mijas', population: 86000 },
    { name: 'Estepona', slug: 'estepona', population: 73000 },
    { name: 'Manilva', slug: 'manilva', population: 16000 },
    { name: 'Sotogrande', slug: 'sotogrande', population: 3000 },
    { name: 'La Línea', slug: 'la-linea', population: 63000 },
    { name: 'Tarifa', slug: 'tarifa', population: 18000 },
    { name: 'Conil', slug: 'conil', population: 22000 },
    { name: 'Chiclana', slug: 'chiclana', population: 85000 },
    { name: 'El Puerto de Santa María', slug: 'puerto-santa-maria', population: 89000 },
    { name: 'Rota', slug: 'rota', population: 29000 },
    { name: 'Chipiona', slug: 'chipiona', population: 19000 },
    { name: 'Sanlúcar de Barrameda', slug: 'sanlucar-barrameda', population: 68000 },
    { name: 'Punta Umbría', slug: 'punta-umbria', population: 15000 },
    { name: 'Isla Cristina', slug: 'isla-cristina', population: 21000 },
    { name: 'Ayamonte', slug: 'ayamonte', population: 21000 },
  ],
  usa: [
    { name: 'New York', slug: 'new-york', population: 8336000 },
    { name: 'Los Angeles', slug: 'los-angeles', population: 3979000 },
    { name: 'Chicago', slug: 'chicago', population: 2693000 },
    { name: 'Miami', slug: 'miami', population: 454000 },
    { name: 'San Francisco', slug: 'san-francisco', population: 873000 },
    { name: 'Denver', slug: 'denver', population: 727000 },
    { name: 'Seattle', slug: 'seattle', population: 737000 },
    { name: 'Austin', slug: 'austin', population: 978000 },
    { name: 'Portland', slug: 'portland', population: 653000 },
    { name: 'San Diego', slug: 'san-diego', population: 1424000 },
  ],
  uk: [
    { name: 'London', slug: 'london', population: 8982000 },
    { name: 'Manchester', slug: 'manchester', population: 553000 },
    { name: 'Birmingham', slug: 'birmingham', population: 1141000 },
    { name: 'Edinburgh', slug: 'edinburgh', population: 527000 },
    { name: 'Bristol', slug: 'bristol', population: 463000 },
    { name: 'Brighton', slug: 'brighton', population: 229000 },
    { name: 'Leeds', slug: 'leeds', population: 793000 },
    { name: 'Glasgow', slug: 'glasgow', population: 633000 },
    { name: 'Liverpool', slug: 'liverpool', population: 498000 },
    { name: 'Sheffield', slug: 'sheffield', population: 584000 },
    { name: 'Newcastle', slug: 'newcastle', population: 302000 },
    { name: 'Nottingham', slug: 'nottingham', population: 321000 },
    { name: 'Southampton', slug: 'southampton', population: 253000 },
    { name: 'Leicester', slug: 'leicester', population: 355000 },
    { name: 'Coventry', slug: 'coventry', population: 371000 },
    { name: 'Cardiff', slug: 'cardiff', population: 362000 },
    { name: 'Belfast', slug: 'belfast', population: 343000 },
    { name: 'Aberdeen', slug: 'aberdeen', population: 196000 },
    { name: 'Cambridge', slug: 'cambridge', population: 124000 },
    { name: 'Oxford', slug: 'oxford', population: 152000 },
    { name: 'York', slug: 'york', population: 210000 },
    { name: 'Bath', slug: 'bath', population: 89000 },
    { name: 'Canterbury', slug: 'canterbury', population: 55000 },
    { name: 'Bournemouth', slug: 'bournemouth', population: 183000 },
    { name: 'Plymouth', slug: 'plymouth', population: 263000 },
    { name: 'Exeter', slug: 'exeter', population: 130000 },
    { name: 'Norwich', slug: 'norwich', population: 141000 },
    { name: 'Reading', slug: 'reading', population: 163000 },
    { name: 'Milton Keynes', slug: 'milton-keynes', population: 229000 },
    { name: 'Swindon', slug: 'swindon', population: 185000 },
    { name: 'Cheltenham', slug: 'cheltenham', population: 117000 },
    { name: 'Gloucester', slug: 'gloucester', population: 129000 },
    { name: 'Worcester', slug: 'worcester', population: 101000 },
    { name: 'Hereford', slug: 'hereford', population: 61000 },
    { name: 'Shrewsbury', slug: 'shrewsbury', population: 72000 },
    { name: 'Chester', slug: 'chester', population: 79000 },
    { name: 'Blackpool', slug: 'blackpool', population: 139000 },
    { name: 'Preston', slug: 'preston', population: 141000 },
    { name: 'Lancaster', slug: 'lancaster', population: 52000 },
    { name: 'Carlisle', slug: 'carlisle', population: 75000 },
    { name: 'Durham', slug: 'durham', population: 48000 },
    { name: 'Sunderland', slug: 'sunderland', population: 174000 },
    { name: 'Middlesbrough', slug: 'middlesbrough', population: 140000 },
    { name: 'Scarborough', slug: 'scarborough', population: 61000 },
    { name: 'Harrogate', slug: 'harrogate', population: 75000 },
    { name: 'Bradford', slug: 'bradford', population: 537000 },
    { name: 'Huddersfield', slug: 'huddersfield', population: 162000 },
    { name: 'Halifax', slug: 'halifax', population: 88000 },
    { name: 'Wakefield', slug: 'wakefield', population: 99000 },
    { name: 'Doncaster', slug: 'doncaster', population: 109000 },
    { name: 'Rotherham', slug: 'rotherham', population: 109000 },
    { name: 'Barnsley', slug: 'barnsley', population: 91000 },
    { name: 'Chesterfield', slug: 'chesterfield', population: 104000 },
    { name: 'Derby', slug: 'derby', population: 257000 },
    { name: 'Lincoln', slug: 'lincoln', population: 100000 },
    { name: 'Peterborough', slug: 'peterborough', population: 203000 },
    { name: 'Ipswich', slug: 'ipswich', population: 137000 },
    { name: 'Colchester', slug: 'colchester', population: 104000 },
    { name: 'Chelmsford', slug: 'chelmsford', population: 111000 },
    { name: 'Southend', slug: 'southend', population: 183000 },
    { name: 'Basildon', slug: 'basildon', population: 107000 },
    { name: 'Luton', slug: 'luton', population: 213000 },
    { name: 'Watford', slug: 'watford', population: 96000 },
    { name: 'St Albans', slug: 'st-albans', population: 147000 },
    { name: 'Stevenage', slug: 'stevenage', population: 87000 },
    { name: 'Guildford', slug: 'guildford', population: 77000 },
    { name: 'Woking', slug: 'woking', population: 105000 },
    { name: 'Crawley', slug: 'crawley', population: 112000 },
    { name: 'Hastings', slug: 'hastings', population: 92000 },
    { name: 'Eastbourne', slug: 'eastbourne', population: 103000 },
    { name: 'Worthing', slug: 'worthing', population: 109000 },
    { name: 'Chichester', slug: 'chichester', population: 31000 },
    { name: 'Portsmouth', slug: 'portsmouth', population: 205000 },
    { name: 'Winchester', slug: 'winchester', population: 45000 },
    { name: 'Salisbury', slug: 'salisbury', population: 45000 },
    { name: 'Poole', slug: 'poole', population: 151000 },
    { name: 'Weymouth', slug: 'weymouth', population: 53000 },
    { name: 'Torquay', slug: 'torquay', population: 65000 },
    { name: 'Paignton', slug: 'paignton', population: 50000 },
    { name: 'Newquay', slug: 'newquay', population: 22000 },
    { name: 'Truro', slug: 'truro', population: 19000 },
    { name: 'Falmouth', slug: 'falmouth', population: 22000 },
    { name: 'Penzance', slug: 'penzance', population: 21000 },
    { name: 'St Ives', slug: 'st-ives', population: 12000 },
    { name: 'Swansea', slug: 'swansea', population: 246000 },
    { name: 'Newport', slug: 'newport', population: 151000 },
    { name: 'Wrexham', slug: 'wrexham', population: 65000 },
    { name: 'Bangor', slug: 'bangor', population: 18000 },
    { name: 'Inverness', slug: 'inverness', population: 47000 },
    { name: 'Dundee', slug: 'dundee', population: 148000 },
    { name: 'Perth', slug: 'perth-uk', population: 47000 },
    { name: 'Stirling', slug: 'stirling', population: 37000 },
    { name: 'St Andrews', slug: 'st-andrews', population: 17000 },
  ],
  germany: [
    { name: 'Berlin', slug: 'berlin', population: 3645000 },
    { name: 'Hamburg', slug: 'hamburg', population: 1841000 },
    { name: 'München', slug: 'muenchen', population: 1472000 },
    { name: 'Köln', slug: 'koeln', population: 1086000 },
    { name: 'Frankfurt', slug: 'frankfurt', population: 753000 },
    { name: 'Düsseldorf', slug: 'duesseldorf', population: 619000 },
    { name: 'Stuttgart', slug: 'stuttgart', population: 635000 },
    { name: 'Leipzig', slug: 'leipzig', population: 593000 },
    { name: 'Dortmund', slug: 'dortmund', population: 588000 },
    { name: 'Essen', slug: 'essen', population: 583000 },
    { name: 'Bremen', slug: 'bremen', population: 567000 },
    { name: 'Dresden', slug: 'dresden', population: 556000 },
    { name: 'Hannover', slug: 'hannover', population: 536000 },
    { name: 'Nürnberg', slug: 'nuernberg', population: 518000 },
    { name: 'Duisburg', slug: 'duisburg', population: 498000 },
    { name: 'Bochum', slug: 'bochum', population: 365000 },
    { name: 'Wuppertal', slug: 'wuppertal', population: 355000 },
    { name: 'Bielefeld', slug: 'bielefeld', population: 334000 },
    { name: 'Bonn', slug: 'bonn', population: 330000 },
    { name: 'Münster', slug: 'muenster', population: 315000 },
    { name: 'Karlsruhe', slug: 'karlsruhe', population: 312000 },
    { name: 'Mannheim', slug: 'mannheim', population: 310000 },
    { name: 'Augsburg', slug: 'augsburg', population: 296000 },
    { name: 'Wiesbaden', slug: 'wiesbaden', population: 278000 },
    { name: 'Gelsenkirchen', slug: 'gelsenkirchen', population: 260000 },
    { name: 'Mönchengladbach', slug: 'moenchengladbach', population: 261000 },
    { name: 'Braunschweig', slug: 'braunschweig', population: 249000 },
    { name: 'Chemnitz', slug: 'chemnitz', population: 247000 },
    { name: 'Kiel', slug: 'kiel', population: 247000 },
    { name: 'Aachen', slug: 'aachen', population: 249000 },
    { name: 'Halle', slug: 'halle', population: 239000 },
    { name: 'Magdeburg', slug: 'magdeburg', population: 238000 },
    { name: 'Freiburg', slug: 'freiburg', population: 231000 },
    { name: 'Krefeld', slug: 'krefeld', population: 227000 },
    { name: 'Lübeck', slug: 'luebeck', population: 217000 },
    { name: 'Mainz', slug: 'mainz', population: 218000 },
    { name: 'Erfurt', slug: 'erfurt', population: 214000 },
    { name: 'Rostock', slug: 'rostock', population: 209000 },
    { name: 'Kassel', slug: 'kassel', population: 202000 },
    { name: 'Hagen', slug: 'hagen', population: 189000 },
    { name: 'Potsdam', slug: 'potsdam', population: 183000 },
    { name: 'Saarbrücken', slug: 'saarbruecken', population: 181000 },
    { name: 'Hamm', slug: 'hamm', population: 179000 },
    { name: 'Ludwigshafen', slug: 'ludwigshafen', population: 172000 },
    { name: 'Oldenburg', slug: 'oldenburg', population: 170000 },
    { name: 'Osnabrück', slug: 'osnabrueck', population: 165000 },
    { name: 'Leverkusen', slug: 'leverkusen', population: 164000 },
    { name: 'Heidelberg', slug: 'heidelberg', population: 161000 },
    { name: 'Darmstadt', slug: 'darmstadt', population: 159000 },
    { name: 'Regensburg', slug: 'regensburg', population: 153000 },
    { name: 'Würzburg', slug: 'wuerzburg', population: 128000 },
    { name: 'Göttingen', slug: 'goettingen', population: 119000 },
    { name: 'Wolfsburg', slug: 'wolfsburg', population: 124000 },
    { name: 'Ulm', slug: 'ulm', population: 126000 },
    { name: 'Heilbronn', slug: 'heilbronn', population: 126000 },
    { name: 'Pforzheim', slug: 'pforzheim', population: 125000 },
    { name: 'Offenbach', slug: 'offenbach', population: 130000 },
    { name: 'Ingolstadt', slug: 'ingolstadt', population: 138000 },
    { name: 'Reutlingen', slug: 'reutlingen', population: 116000 },
    { name: 'Koblenz', slug: 'koblenz', population: 114000 },
    { name: 'Jena', slug: 'jena', population: 111000 },
    { name: 'Trier', slug: 'trier', population: 111000 },
    { name: 'Erlangen', slug: 'erlangen', population: 112000 },
    { name: 'Konstanz', slug: 'konstanz', population: 85000 },
    { name: 'Bamberg', slug: 'bamberg', population: 77000 },
    { name: 'Bayreuth', slug: 'bayreuth', population: 75000 },
    { name: 'Passau', slug: 'passau', population: 53000 },
    { name: 'Lindau', slug: 'lindau', population: 25000 },
    { name: 'Garmisch', slug: 'garmisch', population: 27000 },
    { name: 'Berchtesgaden', slug: 'berchtesgaden', population: 8000 },
    { name: 'Sylt', slug: 'sylt', population: 18000 },
    { name: 'Rügen', slug: 'ruegen', population: 65000 },
    { name: 'Usedom', slug: 'usedom', population: 31000 },
  ],
  france: [
    { name: 'Paris', slug: 'paris', population: 2161000 },
    { name: 'Lyon', slug: 'lyon', population: 516000 },
    { name: 'Marseille', slug: 'marseille', population: 861000 },
    { name: 'Bordeaux', slug: 'bordeaux', population: 257000 },
    { name: 'Nice', slug: 'nice', population: 342000 },
    { name: 'Toulouse', slug: 'toulouse', population: 479000 },
    { name: 'Nantes', slug: 'nantes', population: 309000 },
    { name: 'Strasbourg', slug: 'strasbourg', population: 280000 },
    { name: 'Montpellier', slug: 'montpellier', population: 285000 },
    { name: 'Lille', slug: 'lille', population: 233000 },
    { name: 'Rennes', slug: 'rennes', population: 216000 },
    { name: 'Reims', slug: 'reims', population: 182000 },
    { name: 'Le Havre', slug: 'le-havre', population: 172000 },
    { name: 'Saint-Étienne', slug: 'saint-etienne', population: 172000 },
    { name: 'Toulon', slug: 'toulon', population: 171000 },
    { name: 'Grenoble', slug: 'grenoble', population: 158000 },
    { name: 'Dijon', slug: 'dijon', population: 156000 },
    { name: 'Angers', slug: 'angers', population: 152000 },
    { name: 'Nîmes', slug: 'nimes', population: 151000 },
    { name: 'Aix-en-Provence', slug: 'aix-en-provence', population: 143000 },
    { name: 'Brest', slug: 'brest', population: 139000 },
    { name: 'Le Mans', slug: 'le-mans', population: 144000 },
    { name: 'Amiens', slug: 'amiens', population: 134000 },
    { name: 'Tours', slug: 'tours', population: 136000 },
    { name: 'Limoges', slug: 'limoges', population: 132000 },
    { name: 'Clermont-Ferrand', slug: 'clermont-ferrand', population: 143000 },
    { name: 'Villeurbanne', slug: 'villeurbanne', population: 150000 },
    { name: 'Besançon', slug: 'besancon', population: 117000 },
    { name: 'Orléans', slug: 'orleans', population: 116000 },
    { name: 'Metz', slug: 'metz', population: 118000 },
    { name: 'Rouen', slug: 'rouen', population: 111000 },
    { name: 'Mulhouse', slug: 'mulhouse', population: 109000 },
    { name: 'Perpignan', slug: 'perpignan', population: 121000 },
    { name: 'Caen', slug: 'caen', population: 106000 },
    { name: 'Nancy', slug: 'nancy', population: 105000 },
    { name: 'Avignon', slug: 'avignon', population: 92000 },
    { name: 'Cannes', slug: 'cannes', population: 74000 },
    { name: 'Saint-Tropez', slug: 'saint-tropez', population: 4000 },
    { name: 'Antibes', slug: 'antibes', population: 73000 },
    { name: 'Monaco', slug: 'monaco', population: 39000 },
    { name: 'Biarritz', slug: 'biarritz', population: 25000 },
    { name: 'La Rochelle', slug: 'la-rochelle', population: 77000 },
    { name: 'Arcachon', slug: 'arcachon', population: 11000 },
    { name: 'Saint-Malo', slug: 'saint-malo', population: 46000 },
    { name: 'Deauville', slug: 'deauville', population: 4000 },
    { name: 'Chamonix', slug: 'chamonix', population: 9000 },
    { name: 'Annecy', slug: 'annecy', population: 128000 },
    { name: 'Colmar', slug: 'colmar', population: 69000 },
  ],
  italy: [
    { name: 'Milano', slug: 'milano', population: 1352000 },
    { name: 'Roma', slug: 'roma', population: 2873000 },
    { name: 'Firenze', slug: 'firenze', population: 382000 },
    { name: 'Torino', slug: 'torino', population: 870000 },
    { name: 'Napoli', slug: 'napoli', population: 967000 },
    { name: 'Palermo', slug: 'palermo', population: 663000 },
    { name: 'Genova', slug: 'genova', population: 580000 },
    { name: 'Bologna', slug: 'bologna', population: 392000 },
    { name: 'Bari', slug: 'bari', population: 326000 },
    { name: 'Catania', slug: 'catania', population: 311000 },
    { name: 'Venezia', slug: 'venezia', population: 261000 },
    { name: 'Verona', slug: 'verona', population: 259000 },
    { name: 'Messina', slug: 'messina', population: 232000 },
    { name: 'Padova', slug: 'padova', population: 211000 },
    { name: 'Trieste', slug: 'trieste', population: 204000 },
    { name: 'Brescia', slug: 'brescia', population: 196000 },
    { name: 'Parma', slug: 'parma', population: 196000 },
    { name: 'Taranto', slug: 'taranto', population: 191000 },
    { name: 'Modena', slug: 'modena', population: 186000 },
    { name: 'Reggio Calabria', slug: 'reggio-calabria', population: 181000 },
    { name: 'Reggio Emilia', slug: 'reggio-emilia', population: 172000 },
    { name: 'Perugia', slug: 'perugia', population: 166000 },
    { name: 'Livorno', slug: 'livorno', population: 158000 },
    { name: 'Ravenna', slug: 'ravenna', population: 159000 },
    { name: 'Cagliari', slug: 'cagliari', population: 154000 },
    { name: 'Foggia', slug: 'foggia', population: 151000 },
    { name: 'Rimini', slug: 'rimini', population: 150000 },
    { name: 'Salerno', slug: 'salerno', population: 134000 },
    { name: 'Ferrara', slug: 'ferrara', population: 132000 },
    { name: 'Sassari', slug: 'sassari', population: 127000 },
    { name: 'Siracusa', slug: 'siracusa', population: 122000 },
    { name: 'Pescara', slug: 'pescara', population: 121000 },
    { name: 'Monza', slug: 'monza', population: 124000 },
    { name: 'Bergamo', slug: 'bergamo', population: 121000 },
    { name: 'Trento', slug: 'trento', population: 118000 },
    { name: 'Vicenza', slug: 'vicenza', population: 112000 },
    { name: 'Terni', slug: 'terni', population: 111000 },
    { name: 'Bolzano', slug: 'bolzano', population: 107000 },
    { name: 'Novara', slug: 'novara', population: 104000 },
    { name: 'Piacenza', slug: 'piacenza', population: 103000 },
    { name: 'Ancona', slug: 'ancona', population: 101000 },
    { name: 'Lecce', slug: 'lecce', population: 95000 },
    { name: 'Pisa', slug: 'pisa', population: 91000 },
    { name: 'Lucca', slug: 'lucca', population: 89000 },
    { name: 'Arezzo', slug: 'arezzo', population: 100000 },
    { name: 'Siena', slug: 'siena', population: 54000 },
    { name: 'Como', slug: 'como', population: 84000 },
    { name: 'Sorrento', slug: 'sorrento', population: 16000 },
    { name: 'Positano', slug: 'positano', population: 4000 },
    { name: 'Amalfi', slug: 'amalfi', population: 5000 },
    { name: 'Capri', slug: 'capri', population: 14000 },
    { name: 'Taormina', slug: 'taormina', population: 11000 },
    { name: 'Portofino', slug: 'portofino', population: 400 },
    { name: 'Cinque Terre', slug: 'cinque-terre', population: 4000 },
    { name: 'San Gimignano', slug: 'san-gimignano', population: 8000 },
    { name: 'Cortina', slug: 'cortina', population: 6000 },
  ],
  netherlands: [
    { name: 'Amsterdam', slug: 'amsterdam', population: 873000 },
    { name: 'Rotterdam', slug: 'rotterdam', population: 651000 },
    { name: 'Den Haag', slug: 'den-haag', population: 545000 },
    { name: 'Utrecht', slug: 'utrecht', population: 358000 },
    { name: 'Eindhoven', slug: 'eindhoven', population: 234000 },
    { name: 'Groningen', slug: 'groningen', population: 233000 },
    { name: 'Tilburg', slug: 'tilburg', population: 219000 },
    { name: 'Almere', slug: 'almere', population: 212000 },
    { name: 'Breda', slug: 'breda', population: 184000 },
    { name: 'Nijmegen', slug: 'nijmegen', population: 177000 },
    { name: 'Apeldoorn', slug: 'apeldoorn', population: 163000 },
    { name: 'Haarlem', slug: 'haarlem', population: 161000 },
    { name: 'Arnhem', slug: 'arnhem', population: 159000 },
    { name: 'Enschede', slug: 'enschede', population: 159000 },
    { name: 'Amersfoort', slug: 'amersfoort', population: 157000 },
    { name: 'Zaanstad', slug: 'zaanstad', population: 155000 },
    { name: 'Haarlemmermeer', slug: 'haarlemmermeer', population: 154000 },
    { name: 's-Hertogenbosch', slug: 's-hertogenbosch', population: 154000 },
    { name: 'Zwolle', slug: 'zwolle', population: 129000 },
    { name: 'Zoetermeer', slug: 'zoetermeer', population: 125000 },
    { name: 'Leiden', slug: 'leiden', population: 124000 },
    { name: 'Maastricht', slug: 'maastricht', population: 121000 },
    { name: 'Dordrecht', slug: 'dordrecht', population: 119000 },
    { name: 'Ede', slug: 'ede', population: 117000 },
    { name: 'Alphen aan den Rijn', slug: 'alphen-aan-den-rijn', population: 111000 },
    { name: 'Alkmaar', slug: 'alkmaar', population: 109000 },
    { name: 'Delft', slug: 'delft', population: 103000 },
    { name: 'Emmen', slug: 'emmen', population: 107000 },
    { name: 'Deventer', slug: 'deventer', population: 101000 },
    { name: 'Leeuwarden', slug: 'leeuwarden', population: 123000 },
    { name: 'Venlo', slug: 'venlo', population: 101000 },
    { name: 'Hilversum', slug: 'hilversum', population: 90000 },
    { name: 'Heerlen', slug: 'heerlen', population: 87000 },
    { name: 'Oss', slug: 'oss', population: 92000 },
    { name: 'Schiedam', slug: 'schiedam', population: 78000 },
    { name: 'Spijkenisse', slug: 'spijkenisse', population: 72000 },
    { name: 'Helmond', slug: 'helmond', population: 92000 },
    { name: 'Purmerend', slug: 'purmerend', population: 81000 },
    { name: 'Roosendaal', slug: 'roosendaal', population: 77000 },
    { name: 'Vlaardingen', slug: 'vlaardingen', population: 72000 },
    { name: 'Gouda', slug: 'gouda', population: 73000 },
    { name: 'Hoorn', slug: 'hoorn', population: 73000 },
    { name: 'Velsen', slug: 'velsen', population: 68000 },
    { name: 'Bergen op Zoom', slug: 'bergen-op-zoom', population: 67000 },
    { name: 'Capelle aan den IJssel', slug: 'capelle-aan-den-ijssel', population: 67000 },
    { name: 'Katwijk', slug: 'katwijk', population: 65000 },
    { name: 'Zeist', slug: 'zeist', population: 64000 },
    { name: 'Nieuwegein', slug: 'nieuwegein', population: 63000 },
    { name: 'Hardenberg', slug: 'hardenberg', population: 61000 },
    { name: 'Veenendaal', slug: 'veenendaal', population: 67000 },
  ],
  portugal: [
    { name: 'Lisboa', slug: 'lisboa', population: 545000 },
    { name: 'Porto', slug: 'porto', population: 237000 },
    { name: 'Vila Nova de Gaia', slug: 'vila-nova-gaia', population: 302000 },
    { name: 'Amadora', slug: 'amadora', population: 175000 },
    { name: 'Braga', slug: 'braga', population: 193000 },
    { name: 'Setúbal', slug: 'setubal', population: 121000 },
    { name: 'Coimbra', slug: 'coimbra', population: 143000 },
    { name: 'Funchal', slug: 'funchal', population: 112000 },
    { name: 'Almada', slug: 'almada', population: 174000 },
    { name: 'Queluz', slug: 'queluz', population: 103000 },
    { name: 'Agualva-Cacém', slug: 'agualva-cacem', population: 81000 },
    { name: 'Aveiro', slug: 'aveiro', population: 78000 },
    { name: 'Évora', slug: 'evora', population: 57000 },
    { name: 'Faro', slug: 'faro', population: 65000 },
    { name: 'Guimarães', slug: 'guimaraes', population: 158000 },
    { name: 'Leiria', slug: 'leiria', population: 127000 },
    { name: 'Matosinhos', slug: 'matosinhos', population: 175000 },
    { name: 'Viseu', slug: 'viseu', population: 99000 },
    { name: 'Cascais', slug: 'cascais', population: 206000 },
    { name: 'Sintra', slug: 'sintra', population: 377000 },
    { name: 'Oeiras', slug: 'oeiras', population: 172000 },
    { name: 'Albufeira', slug: 'albufeira', population: 40000 },
    { name: 'Lagos', slug: 'lagos', population: 31000 },
    { name: 'Portimão', slug: 'portimao', population: 56000 },
    { name: 'Vilamoura', slug: 'vilamoura', population: 14000 },
    { name: 'Tavira', slug: 'tavira', population: 26000 },
    { name: 'Sagres', slug: 'sagres', population: 2000 },
    { name: 'Nazaré', slug: 'nazare', population: 15000 },
    { name: 'Óbidos', slug: 'obidos', population: 12000 },
    { name: 'Peniche', slug: 'peniche', population: 28000 },
    { name: 'Ericeira', slug: 'ericeira', population: 10000 },
    { name: 'Estoril', slug: 'estoril', population: 26000 },
    { name: 'Costa da Caparica', slug: 'costa-caparica', population: 13000 },
    { name: 'Sesimbra', slug: 'sesimbra', population: 49000 },
    { name: 'Tróia', slug: 'troia', population: 1000 },
    { name: 'Comporta', slug: 'comporta', population: 1500 },
  ],
  austria: [
    { name: 'Wien', slug: 'wien', population: 1897000 },
    { name: 'Salzburg', slug: 'salzburg', population: 155000 },
  ],
  'switzerland-de': [
    { name: 'Zürich', slug: 'zuerich', population: 421000 },
    { name: 'Basel', slug: 'basel', population: 177000 },
    { name: 'Bern', slug: 'bern', population: 134000 },
  ],
  canada: [
    { name: 'Toronto', slug: 'toronto', population: 2731000 },
    { name: 'Vancouver', slug: 'vancouver', population: 631000 },
    { name: 'Montreal', slug: 'montreal', population: 1762000 },
  ],
  australia: [
    { name: 'Sydney', slug: 'sydney', population: 5312000 },
    { name: 'Melbourne', slug: 'melbourne', population: 5078000 },
  ],
  ireland: [
    { name: 'Dublin', slug: 'dublin', population: 1173000 },
    { name: 'Cork', slug: 'cork', population: 210000 },
  ],
  'belgium-fr': [
    { name: 'Bruxelles', slug: 'bruxelles', population: 185000 },
  ],
  'belgium-nl': [
    { name: 'Antwerpen', slug: 'antwerpen', population: 529000 },
    { name: 'Gent', slug: 'gent', population: 263000 },
  ],
  'switzerland-fr': [
    { name: 'Genève', slug: 'geneve', population: 201000 },
    { name: 'Lausanne', slug: 'lausanne', population: 139000 },
  ],
  'switzerland-it': [
    { name: 'Lugano', slug: 'lugano', population: 63000 },
  ],
  poland: [
    { name: 'Warszawa', slug: 'warszawa', population: 1790000 },
    { name: 'Kraków', slug: 'krakow', population: 780000 },
  ],
  czechia: [
    { name: 'Praha', slug: 'praha', population: 1309000 },
  ],
  greece: [
    { name: 'Αθήνα', slug: 'athina', population: 664000 },
  ],
};

// =============================================================================
// GAME ROOM PRODUCT CATEGORIES
// =============================================================================

export const CATEGORIES = [
  'mesas-billar',
  'futbolines',
  'dardos',
  'air-hockey',
  'ping-pong',
  'accesorios-juegos',
] as const;

export type Category = typeof CATEGORIES[number];

export const PRODUCT_TYPES: Record<Category, string[]> = {
  'mesas-billar': ['profesional', 'domestica', '7-pies', '8-pies', '9-pies', 'convertible', 'americana', 'inglesa', 'snooker', 'carambola'],
  'futbolines': ['profesional', 'domestico', 'ninos', 'exterior', 'plegable', 'madera', 'metal', 'led', 'monedero', 'torneo'],
  'dardos': ['electronica', 'tradicional', 'profesional', 'led', 'bluetooth', 'torneo', 'diana-sisal', 'diana-plastico', 'set-completo', 'accesorios'],
  'air-hockey': ['profesional', 'domestico', 'ninos', 'led', 'electronico', 'plegable', 'grande', 'mediano', 'pequeno', 'arcade'],
  'ping-pong': ['profesional', 'domestica', 'exterior', 'plegable', 'mini', 'torneo', 'red-incluida', 'ruedas', 'compacta', 'convertible'],
  'accesorios-juegos': ['bolas-billar', 'tacos', 'tizas', 'fundas', 'lamparas', 'marcadores', 'repuestos', 'mantenimiento', 'decoracion', 'kits'],
};

// =============================================================================
// CATEGORY TRANSLATIONS
// =============================================================================

export const CATEGORY_TRANSLATIONS: Record<Locale, Record<Category, string>> = {
  es: {
    'mesas-billar': 'mesas de billar',
    'futbolines': 'futbolines',
    'dardos': 'dianas y dardos',
    'air-hockey': 'air hockey',
    'ping-pong': 'mesas ping pong',
    'accesorios-juegos': 'accesorios juegos',
  },
  en: {
    'mesas-billar': 'pool tables',
    'futbolines': 'foosball tables',
    'dardos': 'dart boards',
    'air-hockey': 'air hockey tables',
    'ping-pong': 'ping pong tables',
    'accesorios-juegos': 'game accessories',
  },
  de: {
    'mesas-billar': 'billardtische',
    'futbolines': 'tischfussball',
    'dardos': 'dartscheiben',
    'air-hockey': 'airhockey tische',
    'ping-pong': 'tischtennisplatten',
    'accesorios-juegos': 'spielzubehoer',
  },
  fr: {
    'mesas-billar': 'tables de billard',
    'futbolines': 'baby foot',
    'dardos': 'cibles flechettes',
    'air-hockey': 'tables air hockey',
    'ping-pong': 'tables ping pong',
    'accesorios-juegos': 'accessoires jeux',
  },
  it: {
    'mesas-billar': 'tavoli da biliardo',
    'futbolines': 'calcio balilla',
    'dardos': 'bersagli freccette',
    'air-hockey': 'tavoli air hockey',
    'ping-pong': 'tavoli ping pong',
    'accesorios-juegos': 'accessori giochi',
  },
  pt: {
    'mesas-billar': 'mesas de bilhar',
    'futbolines': 'matraquilhos',
    'dardos': 'alvos dardos',
    'air-hockey': 'mesas air hockey',
    'ping-pong': 'mesas ping pong',
    'accesorios-juegos': 'acessorios jogos',
  },
  nl: {
    'mesas-billar': 'pooltafels',
    'futbolines': 'tafelvoetbal',
    'dardos': 'dartborden',
    'air-hockey': 'airhockey tafels',
    'ping-pong': 'tafeltennistafels',
    'accesorios-juegos': 'spel accessoires',
  },
  pl: {
    'mesas-billar': 'stoly bilardowe',
    'futbolines': 'pilkarzyki',
    'dardos': 'tarcze do darta',
    'air-hockey': 'stoly air hockey',
    'ping-pong': 'stoly do ping ponga',
    'accesorios-juegos': 'akcesoria do gier',
  },
  cs: {
    'mesas-billar': 'kulecnikove stoly',
    'futbolines': 'stolni fotbal',
    'dardos': 'sipkove terce',
    'air-hockey': 'air hockey stoly',
    'ping-pong': 'stolni tenis',
    'accesorios-juegos': 'herni prislusenstvi',
  },
  el: {
    'mesas-billar': 'trapezi mpiliardou',
    'futbolines': 'podosfairakia',
    'dardos': 'stochoi velakia',
    'air-hockey': 'trapezi air hockey',
    'ping-pong': 'trapezi ping pong',
    'accesorios-juegos': 'aksesouarpaixnidion',
  },
};

// =============================================================================
// SEARCH INTENTS - High Intent Keywords
// =============================================================================

export const SEARCH_INTENTS = [
  'buy', 'best', 'cheap', 'premium', 'professional', 'online', 'delivery',
  'shop', 'store', 'price', 'quality', 'home', 'for-sale', 'compare',
  'guide', 'install', 'reviews', 'near-me', 'wholesale', 'used'
] as const;

export type SearchIntent = typeof SEARCH_INTENTS[number];

export const INTENT_TRANSLATIONS: Record<Locale, Record<SearchIntent, string>> = {
  es: {
    buy: 'comprar', best: 'mejor', cheap: 'barato', premium: 'premium', professional: 'profesional',
    online: 'online', delivery: 'envio', shop: 'tienda', store: 'tienda', price: 'precio',
    quality: 'calidad', home: 'para-casa', 'for-sale': 'en-venta', compare: 'comparar',
    guide: 'guia', install: 'instalacion', reviews: 'opiniones', 'near-me': 'cerca-de-mi',
    wholesale: 'mayorista', used: 'segunda-mano'
  },
  en: {
    buy: 'buy', best: 'best', cheap: 'cheap', premium: 'premium', professional: 'professional',
    online: 'online', delivery: 'delivery', shop: 'shop', store: 'store', price: 'price',
    quality: 'quality', home: 'for-home', 'for-sale': 'for-sale', compare: 'compare',
    guide: 'guide', install: 'installation', reviews: 'reviews', 'near-me': 'near-me',
    wholesale: 'wholesale', used: 'used'
  },
  de: {
    buy: 'kaufen', best: 'beste', cheap: 'guenstig', premium: 'premium', professional: 'professionell',
    online: 'online', delivery: 'lieferung', shop: 'shop', store: 'geschaeft', price: 'preis',
    quality: 'qualitaet', home: 'fuer-zuhause', 'for-sale': 'zu-verkaufen', compare: 'vergleichen',
    guide: 'ratgeber', install: 'installation', reviews: 'bewertungen', 'near-me': 'in-der-naehe',
    wholesale: 'grosshandel', used: 'gebraucht'
  },
  fr: {
    buy: 'acheter', best: 'meilleur', cheap: 'pas-cher', premium: 'premium', professional: 'professionnel',
    online: 'en-ligne', delivery: 'livraison', shop: 'boutique', store: 'magasin', price: 'prix',
    quality: 'qualite', home: 'pour-maison', 'for-sale': 'a-vendre', compare: 'comparer',
    guide: 'guide', install: 'installation', reviews: 'avis', 'near-me': 'pres-de-moi',
    wholesale: 'grossiste', used: 'occasion'
  },
  it: {
    buy: 'comprare', best: 'migliore', cheap: 'economico', premium: 'premium', professional: 'professionale',
    online: 'online', delivery: 'consegna', shop: 'negozio', store: 'negozio', price: 'prezzo',
    quality: 'qualita', home: 'per-casa', 'for-sale': 'in-vendita', compare: 'confronto',
    guide: 'guida', install: 'installazione', reviews: 'recensioni', 'near-me': 'vicino-a-me',
    wholesale: 'ingrosso', used: 'usato'
  },
  pt: {
    buy: 'comprar', best: 'melhor', cheap: 'barato', premium: 'premium', professional: 'profissional',
    online: 'online', delivery: 'entrega', shop: 'loja', store: 'loja', price: 'preco',
    quality: 'qualidade', home: 'para-casa', 'for-sale': 'a-venda', compare: 'comparar',
    guide: 'guia', install: 'instalacao', reviews: 'avaliacoes', 'near-me': 'perto-de-mim',
    wholesale: 'atacado', used: 'usado'
  },
  nl: {
    buy: 'kopen', best: 'beste', cheap: 'goedkoop', premium: 'premium', professional: 'professioneel',
    online: 'online', delivery: 'levering', shop: 'winkel', store: 'winkel', price: 'prijs',
    quality: 'kwaliteit', home: 'voor-thuis', 'for-sale': 'te-koop', compare: 'vergelijken',
    guide: 'gids', install: 'installatie', reviews: 'reviews', 'near-me': 'bij-mij',
    wholesale: 'groothandel', used: 'tweedehands'
  },
  pl: {
    buy: 'kupic', best: 'najlepszy', cheap: 'tani', premium: 'premium', professional: 'profesjonalny',
    online: 'online', delivery: 'dostawa', shop: 'sklep', store: 'sklep', price: 'cena',
    quality: 'jakosc', home: 'do-domu', 'for-sale': 'na-sprzedaz', compare: 'porownaj',
    guide: 'poradnik', install: 'instalacja', reviews: 'opinie', 'near-me': 'blisko-mnie',
    wholesale: 'hurtownia', used: 'uzywany'
  },
  cs: {
    buy: 'koupit', best: 'nejlepsi', cheap: 'levny', premium: 'premium', professional: 'profesionalni',
    online: 'online', delivery: 'doruceni', shop: 'obchod', store: 'obchod', price: 'cena',
    quality: 'kvalita', home: 'domu', 'for-sale': 'na-prodej', compare: 'srovnani',
    guide: 'pruvodce', install: 'instalace', reviews: 'recenze', 'near-me': 'pobliz',
    wholesale: 'velkoobchod', used: 'pouzity'
  },
  el: {
    buy: 'agora', best: 'kalytero', cheap: 'fthino', premium: 'premium', professional: 'epaggelmatiko',
    online: 'online', delivery: 'paradosi', shop: 'katastima', store: 'katastima', price: 'timi',
    quality: 'poiotita', home: 'gia-spiti', 'for-sale': 'pros-polisi', compare: 'sygkrisi',
    guide: 'odigos', install: 'egkatastasi', reviews: 'kritikes', 'near-me': 'konta-mou',
    wholesale: 'chondriki', used: 'metachirismeno'
  },
};

// =============================================================================
// PREPOSITION "IN" TRANSLATIONS
// =============================================================================

export const PREPOSITION_IN: Record<Locale, string> = {
  es: 'en', en: 'in', de: 'in', fr: 'à', it: 'a', pt: 'em', nl: 'in',
  pl: 'w', cs: 'v', el: 'στην'
};

// =============================================================================
// PAGE TRANSLATIONS
// =============================================================================

export const TRANSLATIONS: Record<Locale, {
  hero: { title: string; subtitle: string; cta: string };
  features: { quality: string; qualityDesc: string; shipping: string; shippingDesc: string; support: string; supportDesc: string; lab: string; labDesc: string };
  products: { title: string; viewAll: string };
  categories: { title: string };
  cta: { title: string; subtitle: string; button: string };
  footer: { about: string; contact: string; legal: string; privacy: string; terms: string };
  nav: { home: string; shop: string; about: string; contact: string };
}> = {
  es: {
    hero: { title: 'The Games Room\npara tu Hogar', subtitle: 'Mesas de billar, futbolines profesionales, dianas de dardos y mesas de air hockey. Envio gratis y garantia 2 anos.', cta: 'Ver Catalogo' },
    features: { quality: 'Calidad Premium', qualityDesc: 'Materiales de primera calidad y acabados profesionales', shipping: 'Envio Gratis', shippingDesc: 'Entrega gratuita en toda Espana', support: 'Asesoria Experta', supportDesc: 'Te ayudamos a elegir el modelo perfecto', lab: 'Garantia 2 Anos', labDesc: 'Garantia completa en todos los productos' },
    products: { title: 'Productos Destacados', viewAll: 'Ver Todo' },
    categories: { title: 'Categorias' },
    cta: { title: 'Tu Sala de Juegos Perfecta', subtitle: 'Presupuesto sin compromiso. Envio e instalacion incluidos.', button: 'Solicitar Presupuesto' },
    footer: { about: 'Sobre Nosotros', contact: 'Contacto', legal: 'Aviso Legal', privacy: 'Privacidad', terms: 'Terminos' },
    nav: { home: 'Inicio', shop: 'Catalogo', about: 'Nosotros', contact: 'Contacto' }
  },
  en: {
    hero: { title: 'The Games Room\nfor Your Home', subtitle: 'Pool tables, foosball tables, dart boards and air hockey tables. Free shipping and 2-year warranty.', cta: 'View Catalog' },
    features: { quality: 'Premium Quality', qualityDesc: 'Professional-grade materials and finishes', shipping: 'Free Shipping', shippingDesc: 'Free delivery across Europe', support: 'Expert Guidance', supportDesc: 'We help you choose the perfect model', lab: '2 Year Warranty', labDesc: 'Full warranty on all products' },
    products: { title: 'Featured Products', viewAll: 'View All' },
    categories: { title: 'Categories' },
    cta: { title: 'Your Perfect Game Room', subtitle: 'Free quote. Shipping and installation included.', button: 'Request Quote' },
    footer: { about: 'About Us', contact: 'Contact', legal: 'Legal Notice', privacy: 'Privacy', terms: 'Terms' },
    nav: { home: 'Home', shop: 'Catalog', about: 'About', contact: 'Contact' }
  },
  de: {
    hero: { title: 'The Games Room\nfur Ihr Zuhause', subtitle: 'Billardtische, Tischfussball, Dartscheiben und Airhockey-Tische. Kostenloser Versand und 2 Jahre Garantie.', cta: 'Katalog Ansehen' },
    features: { quality: 'Premium Qualitat', qualityDesc: 'Professionelle Materialien und Verarbeitung', shipping: 'Kostenloser Versand', shippingDesc: 'Kostenlose Lieferung in ganz Europa', support: 'Expertenberatung', supportDesc: 'Wir helfen Ihnen das perfekte Modell zu wahlen', lab: '2 Jahre Garantie', labDesc: 'Volle Garantie auf alle Produkte' },
    products: { title: 'Ausgewahlte Produkte', viewAll: 'Alle Anzeigen' },
    categories: { title: 'Kategorien' },
    cta: { title: 'Ihr Perfektes Spielzimmer', subtitle: 'Kostenloses Angebot. Versand und Installation inklusive.', button: 'Angebot Anfordern' },
    footer: { about: 'Uber Uns', contact: 'Kontakt', legal: 'Impressum', privacy: 'Datenschutz', terms: 'AGB' },
    nav: { home: 'Startseite', shop: 'Katalog', about: 'Uber Uns', contact: 'Kontakt' }
  },
  fr: {
    hero: { title: 'The Games Room\npour Votre Maison', subtitle: 'Tables de billard, baby-foot, cibles de flechettes et tables de air hockey. Livraison gratuite et garantie 2 ans.', cta: 'Voir le Catalogue' },
    features: { quality: 'Qualite Premium', qualityDesc: 'Materiaux professionnels et finitions soignees', shipping: 'Livraison Gratuite', shippingDesc: 'Livraison gratuite dans toute l\'Europe', support: 'Conseil Expert', supportDesc: 'Nous vous aidons a choisir le modele parfait', lab: 'Garantie 2 Ans', labDesc: 'Garantie complete sur tous les produits' },
    products: { title: 'Produits Vedettes', viewAll: 'Voir Tout' },
    categories: { title: 'Categories' },
    cta: { title: 'Votre Salle de Jeux Parfaite', subtitle: 'Devis gratuit. Livraison et installation incluses.', button: 'Demander un Devis' },
    footer: { about: 'A Propos', contact: 'Contact', legal: 'Mentions Legales', privacy: 'Confidentialite', terms: 'CGV' },
    nav: { home: 'Accueil', shop: 'Catalogue', about: 'A Propos', contact: 'Contact' }
  },
  it: {
    hero: { title: 'The Games Room\nper la Tua Casa', subtitle: 'Tavoli da biliardo, calcio balilla, bersagli per freccette e tavoli da air hockey. Spedizione gratuita e garanzia 2 anni.', cta: 'Vedi Catalogo' },
    features: { quality: 'Qualita Premium', qualityDesc: 'Materiali professionali e finiture di pregio', shipping: 'Spedizione Gratuita', shippingDesc: 'Consegna gratuita in tutta Europa', support: 'Consulenza Esperta', supportDesc: 'Ti aiutiamo a scegliere il modello perfetto', lab: 'Garanzia 2 Anni', labDesc: 'Garanzia completa su tutti i prodotti' },
    products: { title: 'Prodotti in Evidenza', viewAll: 'Vedi Tutto' },
    categories: { title: 'Categorie' },
    cta: { title: 'La Tua Sala Giochi Perfetta', subtitle: 'Preventivo gratuito. Spedizione e installazione incluse.', button: 'Richiedi Preventivo' },
    footer: { about: 'Chi Siamo', contact: 'Contatto', legal: 'Note Legali', privacy: 'Privacy', terms: 'Termini' },
    nav: { home: 'Home', shop: 'Catalogo', about: 'Chi Siamo', contact: 'Contatto' }
  },
  pt: {
    hero: { title: 'The Games Room\npara a Sua Casa', subtitle: 'Mesas de bilhar, matraquilhos, alvos de dardos e mesas de air hockey. Envio gratis e garantia 2 anos.', cta: 'Ver Catalogo' },
    features: { quality: 'Qualidade Premium', qualityDesc: 'Materiais profissionais e acabamentos de qualidade', shipping: 'Envio Gratis', shippingDesc: 'Entrega gratuita em toda a Europa', support: 'Orientacao Especializada', supportDesc: 'Ajudamos a escolher o modelo perfeito', lab: 'Garantia 2 Anos', labDesc: 'Garantia completa em todos os produtos' },
    products: { title: 'Produtos em Destaque', viewAll: 'Ver Tudo' },
    categories: { title: 'Categorias' },
    cta: { title: 'A Sua Sala de Jogos Perfeita', subtitle: 'Orcamento gratis. Envio e instalacao incluidos.', button: 'Pedir Orcamento' },
    footer: { about: 'Sobre Nos', contact: 'Contato', legal: 'Aviso Legal', privacy: 'Privacidade', terms: 'Termos' },
    nav: { home: 'Inicio', shop: 'Catalogo', about: 'Sobre', contact: 'Contato' }
  },
  nl: {
    hero: { title: 'The Games Room\nvoor Uw Huis', subtitle: 'Pooltafels, tafelvoetbal, dartborden en airhockey tafels. Gratis verzending en 2 jaar garantie.', cta: 'Bekijk Catalogus' },
    features: { quality: 'Premium Kwaliteit', qualityDesc: 'Professionele materialen en afwerking', shipping: 'Gratis Verzending', shippingDesc: 'Gratis levering in heel Europa', support: 'Expert Advies', supportDesc: 'Wij helpen u het perfecte model te kiezen', lab: '2 Jaar Garantie', labDesc: 'Volledige garantie op alle producten' },
    products: { title: 'Uitgelichte Producten', viewAll: 'Bekijk Alles' },
    categories: { title: 'Categorieen' },
    cta: { title: 'Uw Perfecte Speelkamer', subtitle: 'Gratis offerte. Verzending en installatie inbegrepen.', button: 'Offerte Aanvragen' },
    footer: { about: 'Over Ons', contact: 'Contact', legal: 'Juridisch', privacy: 'Privacy', terms: 'Voorwaarden' },
    nav: { home: 'Home', shop: 'Catalogus', about: 'Over Ons', contact: 'Contact' }
  },
  pl: {
    hero: { title: 'The Games Room\ndla Twojego Domu', subtitle: 'Stoly bilardowe, pilkarzyki, tarcze do darta i stoly do air hockey. Darmowa wysylka i gwarancja 2 lata.', cta: 'Zobacz Katalog' },
    features: { quality: 'Jakosc Premium', qualityDesc: 'Profesjonalne materialy i wykonczenie', shipping: 'Darmowa Wysylka', shippingDesc: 'Darmowa dostawa w calej Europie', support: 'Porada Eksperta', supportDesc: 'Pomagamy wybrac idealny model', lab: 'Gwarancja 2 Lata', labDesc: 'Pelna gwarancja na wszystkie produkty' },
    products: { title: 'Wyrozniamy Produkty', viewAll: 'Zobacz Wszystko' },
    categories: { title: 'Kategorie' },
    cta: { title: 'Twoj Idealny Pokoj Gier', subtitle: 'Bezplatna wycena. Wysylka i instalacja w cenie.', button: 'Popros o Wycene' },
    footer: { about: 'O Nas', contact: 'Kontakt', legal: 'Nota Prawna', privacy: 'Prywatnosc', terms: 'Regulamin' },
    nav: { home: 'Strona glowna', shop: 'Katalog', about: 'O Nas', contact: 'Kontakt' }
  },
  cs: {
    hero: { title: 'The Games Room\npro Vas Domov', subtitle: 'Kulecnikove stoly, stolni fotbaly, sipkove tarce a stoly na air hockey. Doprava zdarma a zaruka 2 roky.', cta: 'Zobrazit Katalog' },
    features: { quality: 'Premium Kvalita', qualityDesc: 'Profesionalni materialy a zpracovani', shipping: 'Doprava Zdarma', shippingDesc: 'Doprava zdarma po cele Evrope', support: 'Odborne Poradenstvi', supportDesc: 'Pomuzeme vam vybrat idealni model', lab: 'Zaruka 2 Roky', labDesc: 'Plna zaruka na vsechny produkty' },
    products: { title: 'Vybrany Sortiment', viewAll: 'Zobrazit Vse' },
    categories: { title: 'Kategorie' },
    cta: { title: 'Vas Idealni Herni Pokoj', subtitle: 'Nabidka zdarma. Doprava a instalace v cene.', button: 'Pozadat o Nabidku' },
    footer: { about: 'O Nas', contact: 'Kontakt', legal: 'Pravni Upozorneni', privacy: 'Soukromi', terms: 'Podminky' },
    nav: { home: 'Domu', shop: 'Katalog', about: 'O Nas', contact: 'Kontakt' }
  },
  el: {
    hero: { title: 'The Games Room\ngia to Spiti sas', subtitle: 'Trapezia mpiliardou, podosfairakia, stochoi velakia kai trapezia air hockey. Dorean apostoli kai eggyisi 2 eton.', cta: 'Deite ton Katalogo' },
    features: { quality: 'Premium Poiotita', qualityDesc: 'Epaggelmatika ylika kai finirisma', shipping: 'Dorean Apostoli', shippingDesc: 'Dorean paradosi se oli tin Evropi', support: 'Eidiki Kathodigisi', supportDesc: 'Sas voithame na epilexete to teleio montelo', lab: 'Eggyisi 2 Eton', labDesc: 'Pliri eggyisi se ola ta proionta' },
    products: { title: 'Epilegmena Proionta', viewAll: 'Deite Ola' },
    categories: { title: 'Katigories' },
    cta: { title: 'I Teleia Ethesa Paixnidion', subtitle: 'Dorean prosfora. Apostoli kai egkatastasi perilamvanontai.', button: 'Zitiste Prosfora' },
    footer: { about: 'Sxetika me Emas', contact: 'Epikoinonia', legal: 'Nomiki Simeiosi', privacy: 'Aporrito', terms: 'Oroi' },
    nav: { home: 'Arxiki', shop: 'Katalogos', about: 'Sxetika', contact: 'Epikoinonia' }
  },
};
